# Testing with thrown errors

## Exercise 1

Update [Problem 1](asynchronous-testing.md) from the asynchronous exercises to throw/catch errors if there are any problems with the file access.

## Exercise

Update [Problem 1](synchronous-testing.md) from the synchronous testing exercises to throw/catch errors if the is a division by zero

## Exercise

Update [Problem 2](synchronous-testing.md) from the synchronous testing exercises to throw/catch errors if the input is below zero

## Exercise

Update [Problem 4](synchronous-testing.md) so that all 4 validation criteria can be set and are process when the function is called. Also, have the following conditions throw errors:

- If the maximum is set below minimum, throw error;
- If minimum is set above maximum, throw error;
- If when setting the invalid value array, it shares values with the valid value array, throw error.
- If when setting the valid value array, it shares valies with the invalid value array, throw error.