# Testing with thrown errors

## Exercise 1

Update [Problem 1](asynchronous-testing.md) from the asynchronous exercises to catch thrown errors.